// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/hello': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hello').default>>>>
    }
    '/api/menus/breakfast/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menus/breakfast/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menus/breakfast/[id].put').default>>>>
    }
    '/api/menus/breakfast/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menus/breakfast/create.post').default>>>>
    }
    '/api/menus/breakfast': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menus/breakfast/index.get').default>>>>
    }
    '/api/menus/dinner/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menus/dinner/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menus/dinner/[id].put').default>>>>
    }
    '/api/menus/dinner/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menus/dinner/create.post').default>>>>
    }
    '/api/menus/dinner': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menus/dinner/index.get').default>>>>
    }
    '/api/menus/lunch/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menus/lunch/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menus/lunch/[id].put').default>>>>
    }
    '/api/menus/lunch/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menus/lunch/create.post').default>>>>
    }
    '/api/menus/lunch': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menus/lunch/index.get').default>>>>
    }
    '/api/reservations/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reservations/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reservations/[id].put').default>>>>
    }
    '/api/reservations/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reservations/create.post').default>>>>
    }
    '/api/reservations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reservations/index.get').default>>>>
    }
    '/api/users/create': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/create').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}